### ISSUE TITLE
服务端权限控制问题

### ISSUE THREAD

**Issue by hesling** [bigfool-cn/vue-element-admin-express#2]
您好，请问下服务端接口如何通过权限代码控制权限

**Comment by bigfool-cn** [comment]
根据用户角色分配的权限，返回对应的路由

**Comment by hesling** [comment]
这么简单的吗？那如果我不通过页面，直接PSOTMAN访问接口地址呢？即使我有这个token，但是没有这个权限，是不是也可以查看相应的数据？前端页面控制了，服务端接口不用做权限校验控制？
